[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=62.4.0", "wheel" ]

[project]
authors = [ { email = "PARSER_AUTHOR_EMAIL", name = "seanfroste" } ]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
description = "Tree-sitter grammar for the SPECTRA input language"
keywords = [ "incremental", "parsing", "tree-sitter", "spectra" ]
license.text = "UNLICENSED"
name = "tree-sitter-spectra"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.urls]
Homepage = "https://github.com/seanfroste/tree-sitter-spectra"

[project.optional-dependencies]
core = [ "tree-sitter~=0.24" ]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
